project:
  type: website
  output-dir: docs

website:
  title: "JAMES HONG"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: FYP Project
      - href: visualization.qmd
        text: Data Visualization

format:
  html:
    theme: darkly
    css: styles.css
    toc: false



